import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";

const About: NextPage = () => {
  return (
    <div>
      <Head>
        <title>About</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <p>おれは山岸　岐阜に住んでる</p>
      <p>
        notionとかにちょっとずつ書き込んでいって歩きながらとか書き進めていきます
      </p>
      <a href="https://ripple-shock-17d.notion.site/About-088f2c6e41184775b02a3c6f49c5ced8">
        &gt; notion &lt;
      </a>

      <h2>Links</h2>
      <ul>
        <li>
          <a href="https://www.pinterest.jp/kanapon1105/kanatayamagishi-works/">
            Pinterest
          </a>
        </li>
        <li>
          <a href="https://note.com/painintheass">note</a>
        </li>
        <li>
          <a href="https://www.instagram.com/ymgsknt/">instagram</a>
        </li>
        <li>
          <a href="https://twitter.com/ymgsknt">twitter</a>
        </li>
      </ul>
      <div className="memo">
        <h3>About This Page</h3>
        <p>自己紹介が掲載される</p>
        <h3>Concern</h3>
        <ul>
          <li>自分の履歴ってどこから・どの観点から書いた方がいいんですか？</li>
        </ul>
      </div>
    </div>
  );
};

export default About;
