import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";

const About: NextPage = () => {
  return (
    <div>
      <Head>
        <title>About</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h3>PROFILE</h3>
      <p>Kanata YAMAGISHI</p>
      <p>山岸 奏大</p>
      <h3>CONTACT</h3>
      <p>kntymgs1105(at)gmail.com (at)=@</p>
      <h3>BIO</h3>
      <p>
        1998.11 - born in Chiba, Japan <br />
        2017 - 2022 Department of Computer <br />
        Science, Tokyo University of Science (Tokyo, Japan) <br />
        2022 - Department of Media Creation master course in Institute of
        Advanced Media Arts and Sciences (Gifu, Japan)
      </p>
      <p>
        1998.11 東京都生まれ <br />
        2017 - 2022 東京理科大学 工学部情報工学科 <br />
        2022 - 情報科学芸術大学院大学 修士課程 <br />
      </p>

      <h2>Links</h2>
      <ul>
        <li>
          <a href="https://www.pinterest.jp/kanapon1105/kanatayamagishi-works/">
            Pinterest
          </a>
        </li>
        <li>
          <a href="https://note.com/painintheass">note</a>
        </li>
        <li>
          <a href="https://www.instagram.com/ymgsknt/">instagram</a>
        </li>
        <li>
          <a href="https://twitter.com/ymgsknt">twitter</a>
        </li>
      </ul>
      <div className="memo">
        <h3>About This Page</h3>
        <p>
          自己紹介が掲載される.
          notionとかにちょっとずつ書き込んでいって歩きながらとか書き進めていきます{" "}
          <br />
          <a href="https://ripple-shock-17d.notion.site/About-088f2c6e41184775b02a3c6f49c5ced8">
            &gt; notion &lt;
          </a>
        </p>
        <h3>Concern</h3>
        <ul>
          <li>肩書きに迷っている 候補：</li>
          <ul>
            <li>グラフィックデザイナー</li>
            <li>エンジニア</li>
            <li>デザインリサーチャー</li>
            <li>クリエイティブコーダー</li>
            <li>クリエイティブテクノロジスト（...え？）</li>
            <li>デザインエンジニア</li>
          </ul>
          <li>
            何に迷っているか：
            <ul>
              <li>肩書きが多いとダサい</li>
              <li>肩書きが特殊だとダサい</li>
              <li>
                でもシンプルな肩書きだと外れたことができないんじゃないかとか思ってる
              </li>
            </ul>
          </li>
          <li>
            職歴的なことをどこまで書くかで迷っている　一覧
            <ul>
              <li>2020.8-9 株式会社電通　夏期インターン</li>
              <li>2021.7- 株式会社コネル</li>
              <li>2022.1 株式会社電通　冬期インターン</li>
            </ul>
          </li>
          <li>
            何に迷っているか：
            <ul>
              <li>
                なんか細かいことをいちいち書き込んでるなって思われたらダサい
              </li>
              <li>でも信頼感大事だから載せておきたい</li>
            </ul>
          </li>
        </ul>
      </div>
    </div>
  );
};

export default About;
