import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import Link from "next/link";

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Kanata Yamagishi Works</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          ここから<a href="https://twitter.com/KanataYamagishi">Twitter</a>
          にジャンプします
        </h1>
        <p className={styles.description}>
          Kanata Yamagishi&apos;s Excellent Portfolio: WorkInProgress
        </p>
        <p>
          見てて気になるな〜とかある人はここから -&gt;{" "}
          <a href="https://github.com/k1105/ymgsknt">github</a>
        </p>

        <Link href="/research">Research</Link>
        <Link href="/sketch">Sketch</Link>
        <Link href="/about">About</Link>

        <h2>Work in Progress</h2>
        <ul>
          <li>
            <a href="https://ripple-shock-17d.notion.site/Subject-9817da8d5fe44b81b969fe904d30e77c">
              Subject
            </a>
          </li>
          <li>
            <a href="https://ripple-shock-17d.notion.site/Style-1570bc84ac004e57a6b53dfdedebb0cf">
              Style
            </a>
          </li>
          <li>
            <a href="https://ripple-shock-17d.notion.site/Tech-1ec6fdea3e5e4e5cb06d6158fd1bf0de">
              Tech
            </a>
          </li>
          <li>
            <a href="https://ripple-shock-17d.notion.site/Contents-e241f7816bbe4118bc55cb32f5e2c84e">
              Contents
            </a>
          </li>
          <li>
            <a href="">Memo</a>
          </li>
          <li>
            <a href="https://ripple-shock-17d.notion.site/References-81f416bbc11a4c6a80f0e4c1552af734">
              References
            </a>
          </li>
        </ul>

        <h2>Links</h2>
        <ul>
          <li>
            <a href="https://www.pinterest.jp/kanapon1105/kanatayamagishi-works/">
              Pinterest
            </a>
          </li>
          <li>
            <a href="https://note.com/painintheass">note</a>
          </li>
          <li>
            <a href="https://www.instagram.com/ymgsknt/">instagram</a>
          </li>
          <li>
            <a href="https://twitter.com/ymgsknt">twitter</a>
          </li>
        </ul>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
};

export default Home;
