import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";

const Sketch: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Sketch</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <ul>
        <li>
          <a href="https://k1105.github.io/eee_openhouse_2022/">
            Digitalize(IAMAS OpenHouse2022)
          </a>
        </li>
      </ul>
    </div>
  );
};

export default Sketch;
